//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinkelServiceLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Linq2EntityContainer : DbContext
    {
        public Linq2EntityContainer()
            : base("name=Linq2EntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> USERs { get; set; }
        public virtual DbSet<Item> ITEMs { get; set; }
        public virtual DbSet<Purchase> PURCHASEs { get; set; }
    }
}
