//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinkelServiceLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Purchase
    {
        private User loggedInUser;
        private Item selectedItem;
        private int amount;

        public Purchase()
        {
        }

        public Purchase(User loggedInUser, Item selectedItem, int amount)
        {
            this.loggedInUser = loggedInUser;
            this.selectedItem = selectedItem;
            this.amount = amount;
        }

        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string UserUsername { get; set; }
        [DataMember]
        public short Amount { get; set; }
        [DataMember]
        public string ItemName { get; set; }
        public virtual User User { get; set; }
        [DataMember]
        public virtual Item Item { get; set; }
    }
}
